import { type Page, type Locator } from 'playwright';
import type { InteractiveElement } from '../types.js';

export function escapeAttrValue(s: string): string {
  return s.replace(/["\\]/g, '\\$&');
}

export function resolveLocator(page: Page, resolved: InteractiveElement): Locator {
  // 1. CSS selector (generated by scan: ID-based or path-based nth-of-type chain)
  if (resolved.selector) {
    return page.locator(resolved.selector);
  }
  // 2. label (for input elements)
  if (resolved.label) {
    return page.getByLabel(resolved.label);
  }
  // 3. name attribute
  if (resolved.name) {
    return page.locator(`[name="${escapeAttrValue(resolved.name)}"]`);
  }
  // 4. placeholder
  if (resolved.placeholder) {
    return page.getByPlaceholder(resolved.placeholder);
  }
  // 5. role + text (fallback)
  if (resolved.role && resolved.text && resolved.text.trim()) {
    return page.getByRole(resolved.role as Parameters<Page['getByRole']>[0], { name: resolved.text });
  }
  // 6. text (fallback)
  if (resolved.text && resolved.text.trim()) {
    return page.getByText(resolved.text, { exact: true });
  }
  // 7. none available
  throw new Error(`Cannot resolve locator for element: ${resolved.text ?? resolved.tag}`);
}
